import { BookOpen, CalendarDays, ClipboardCheck, Languages, Star, Sunrise } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';
import { PublicLayout } from '@/components/PublicLayout';
import { PublicPageHeader } from '@/components/PublicPageHeader';
import { useWebsiteSettings } from '@/hooks/use-website-settings';

const defaults = { 'website.academics_intro': 'Our educational system brings together Qur’anic memorisation, Arabic language, Islamic studies, and strong general academics.', 'website.curriculum': 'A structured curriculum develops literacy, numeracy, scientific thinking, Islamic understanding, and practical life skills.', 'website.methodology': 'Teaching combines explanation, practice, revision, discussion, and close attention to each learner.', 'website.assessment': 'Continuous classwork, assignments, tests, examinations, and teacher observations help families understand progress.', 'website.calendar': 'The academic calendar follows the published school sessions and terms, with special Islamic programmes throughout the year.' };
const items = [{ icon: BookOpen, title: 'Curriculum overview', key: 'curriculum' }, { icon: Sunrise, title: 'Qur’an memorisation', key: 'academics_intro' }, { icon: Languages, title: 'Arabic and Islamic studies', key: 'academics_intro' }, { icon: ClipboardCheck, title: 'Assessment system', key: 'assessment' }, { icon: CalendarDays, title: 'Academic calendar', key: 'calendar' }, { icon: Star, title: 'Teaching methodology', key: 'methodology' }];

const Academics = () => { const { t } = useLanguage(); const settings = useWebsiteSettings(defaults); return <PublicLayout><PublicPageHeader eyebrow="Academics" title={t('An education that forms the whole person.', 'تعليم يبني الإنسان المتكامل')}><p className="mt-6 max-w-2xl text-lg leading-8 text-primary-foreground/75">{settings['website.academics_intro']}</p></PublicPageHeader><main className="container py-20"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map(item => <article key={item.title} className="border border-border bg-card p-7 shadow-card"><item.icon className="h-7 w-7 text-primary" strokeWidth={1.7} /><h2 className="mt-12 font-display text-xl font-extrabold">{t(item.title, item.title)}</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">{settings[`website.${item.key}`]}</p></article>)}</div></main></PublicLayout>; };
export default Academics;