import { useEffect, useState } from 'react';
import { ExternalLink, FileText, Image, LayoutDashboard, Loader2, Mail, Newspaper, Plus, Save, School, Sparkles, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { AdminLayout } from '@/components/AdminLayout';
import { useLanguage } from '@/contexts/LanguageContext';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { cn } from '@/lib/utils';

type Section = 'overview' | 'homepage' | 'pages' | 'news' | 'gallery' | 'contact';
type Content = Record<string, string>;

const defaults: Content = {
  schoolName: 'Al-Bari Group Of Schools', schoolNameAr: 'مجموعة مدارس البارئ', heroTitle: 'Rooted in faith. Growing in knowledge.', heroText: 'A welcoming Islamic learning community where Qur’anic values, sound knowledge, and excellent character shape every student’s journey.',
  aboutTitle: 'A madrasah for faith, knowledge, and character.', aboutText: 'Our madrasah brings together Qur’anic learning, strong academics, and tarbiyah in a caring environment.', address: 'Al-Bari Madrasah, Main Campus', email: 'hello@albari.sch.ng', phone: '+234 000 000 0000', officeHours: 'Monday - Friday, 8:00am - 4:00pm',
  whyTitle: 'Why choose Al-Bari Institute?', programTitle: 'Our programmes', programQuran: 'Qur’an and sound learning', programTarbiyah: 'Tarbiyah and good character', programCommunity: 'A trusted family partnership', program4: 'Qualified scholars', program5: 'Academic excellence', program6: 'Safe and supportive community',
  programme1: 'Nursery Madrasah', programme2: 'Primary Madrasah', programme3: 'Secondary Madrasah', programme4: 'Tahfeez Programme', programme5: 'Weekend Classes', programme6: 'Adult Classes',
  statsStudents: '0', statsTeachers: '0', statsGraduates: '0', statsYears: '0', facilities: 'Mosque and prayer hall|Tahfeez hall|Library|ICT room|Playground|Safe classrooms', galleryImages: '/images/school-front.png|/images/school-building.png|/images/school-students.png|/images/school-logo.png', galleryAlbums: 'Classes|Tahfeez|Graduation|Excursions|Qur’an Competition|School Events',
  newsOne: 'Students celebrate another term of learning and growth.', newsTwo: 'Qur’an recitation and Islamic knowledge competition announced.', newsThree: 'Our learning community welcomes families to a new academic session.', newsCategoryOne: 'School News', newsCategoryTwo: 'Competitions', newsCategoryThree: 'Announcements', newsDateOne: 'August 01, 2026', newsDateTwo: 'July 24, 2026', newsDateThree: 'July 12, 2026', events: 'Qur’an Competition|Ramadan Activities|End-of-year Graduation', eventDates: 'Aug 12|Mar 05|Dec 18',
  history: 'Founded to serve families seeking a balanced Islamic education.', mission: 'To provide a safe, excellent, and faith-centred learning environment.', vision: 'To raise a generation grounded in Islam, equipped with knowledge, and ready to serve.', values: 'Faith, excellence, integrity, compassion, discipline, and service.', philosophy: 'We believe education is an amanah. Learning should shape the mind, refine the heart, and equip each student to contribute positively.', headMessage: 'Welcome to our madrasah. We are honoured to partner with families in a journey of learning, worship, and character.', academicsIntro: 'Our educational system brings together Qur’anic memorisation, Arabic language, Islamic studies, and strong general academics.', curriculum: 'A structured curriculum develops literacy, numeracy, scientific thinking, Islamic understanding, and practical life skills.', methodology: 'Teaching combines explanation, practice, revision, discussion, and close attention to each learner.', assessment: 'Continuous classwork, assignments, tests, examinations, and teacher observations help families understand progress.', calendar: 'The academic calendar follows the published school sessions and terms, with special Islamic programmes throughout the year.',
};

const fields = Object.keys(defaults);
const toSettingKey = (field: string) => `website.${field.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`)}`;

const AdminWebsite = () => {
  const { t } = useLanguage();
  const { toast } = useToast();
  const [section, setSection] = useState<Section>('overview');
  const [content, setContent] = useState<Content>(defaults);
  const [saving, setSaving] = useState(false);

  useEffect(() => { supabase.from('school_settings').select('key,value').like('key', 'website.%').then(({ data }) => { const saved = Object.fromEntries((data || []).map(row => [row.key, row.value])); setContent(current => fields.reduce((next, field) => ({ ...next, [field]: saved[toSettingKey(field)] || current[field] }), { ...current })); }); }, []);
  const update = (field: string, value: string) => setContent(current => ({ ...current, [field]: value }));
  const save = async () => { setSaving(true); const { error } = await supabase.from('school_settings').upsert(fields.map(field => ({ key: toSettingKey(field), value: content[field] })), { onConflict: 'key' }); setSaving(false); toast(error ? { title: 'Error', description: error.message, variant: 'destructive' } : { title: 'Saved', description: 'Website content has been updated.' }); };
  const uploadGalleryImage = async (file: File) => { const path = `${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, '-')}`; const { error } = await supabase.storage.from('gallery').upload(path, file); if (error) return toast({ title: 'Upload failed', description: error.message, variant: 'destructive' }); const url = supabase.storage.from('gallery').getPublicUrl(path).data.publicUrl; update('galleryImages', content.galleryImages ? `${content.galleryImages}|${url}` : url); };
  const Field = ({ field, label, area = false }: { field: string; label: string; area?: boolean }) => <div className="space-y-2"><Label>{t(label, label)}</Label>{area ? <textarea value={content[field] || ''} onChange={event => update(field, event.target.value)} className="min-h-[100px] w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm leading-6" /> : <input value={content[field] || ''} onChange={event => update(field, event.target.value)} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm" />}</div>;
  const ListFields = ({ field, label }: { field: string; label: string }) => <div className="space-y-3"><Label>{t(label, label)}</Label>{field === 'galleryImages' && <input type="file" accept="image/*" multiple onChange={event => Array.from(event.target.files || []).forEach(uploadGalleryImage)} />}{content[field].split('|').map((item, index) => <div key={`${field}-${index}`} className="flex gap-2"><input value={item} onChange={event => { const items = content[field].split('|'); items[index] = event.target.value; update(field, items.join('|')); }} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm" /><button type="button" onClick={() => update(field, content[field].split('|').filter((_, itemIndex) => itemIndex !== index).join('|'))} className="rounded-lg border border-border px-3 text-muted-foreground hover:text-destructive"><Trash2 className="h-4 w-4" /></button></div>)}<Button type="button" variant="outline" size="sm" onClick={() => update(field, `${content[field]}|New item`)}><Plus className="mr-2 h-4 w-4" />{t('Add item', 'إضافة عنصر')}</Button></div>;
  const tabs = [{ id: 'overview', icon: LayoutDashboard, label: 'Overview' }, { id: 'homepage', icon: Sparkles, label: 'Homepage' }, { id: 'pages', icon: FileText, label: 'Pages' }, { id: 'news', icon: Newspaper, label: 'News & Events' }, { id: 'gallery', icon: Image, label: 'Gallery' }, { id: 'contact', icon: Mail, label: 'Contact' }] as const;
  const newsRows = [['newsOne', 'newsCategoryOne', 'newsDateOne'], ['newsTwo', 'newsCategoryTwo', 'newsDateTwo'], ['newsThree', 'newsCategoryThree', 'newsDateThree']];
  return <AdminLayout><div className="mx-auto max-w-6xl space-y-6 pb-20"><header className="flex flex-col justify-between gap-4 border-b border-border pb-6 md:flex-row md:items-end"><div><p className="eyebrow text-primary">{t('Content management', 'إدارة المحتوى')}</p><h1 className="mt-2 font-display text-3xl font-extrabold">{t('Public website', 'الموقع العام')}</h1><p className="mt-2 text-sm text-muted-foreground">{t('Manage the public institute website by section.', 'إدارة موقع المعهد العام حسب الأقسام.')}</p></div><div className="flex gap-2"><Link to="/" className="inline-flex h-10 items-center gap-2 rounded-lg border border-border px-3 text-xs font-bold hover:bg-muted"><ExternalLink className="h-4 w-4" />{t('View website', 'عرض الموقع')}</Link><Button onClick={save} disabled={saving} className="h-10 rounded-lg">{saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}{t('Save changes', 'حفظ التغييرات')}</Button></div></header><div className="grid gap-6 lg:grid-cols-[220px_1fr]"><nav className="flex gap-1 overflow-x-auto lg:block lg:space-y-1">{tabs.map(tab => <button key={tab.id} onClick={() => setSection(tab.id)} className={cn('flex shrink-0 items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-semibold transition-colors lg:w-full', section === tab.id ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted hover:text-foreground')}><tab.icon className="h-4 w-4" />{t(tab.label, tab.label)}</button>)}</nav><main className="min-w-0 rounded-xl border border-border bg-card p-5 shadow-card md:p-8"><div className="mb-7 flex items-center gap-3 border-b border-border pb-5"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><School className="h-5 w-5" /></div><div><h2 className="font-display text-xl font-extrabold">{t(tabs.find(tab => tab.id === section)?.label || 'Overview', tabs.find(tab => tab.id === section)?.label || 'Overview')}</h2><p className="text-sm text-muted-foreground">{t('Edit this part of the public website.', 'حرر هذا الجزء من الموقع العام.')}</p></div></div>
{section === 'overview' && <div className="space-y-6"><div className="rounded-lg bg-muted/60 p-4 text-sm text-muted-foreground">{t('Control the institute identity and the first message visitors see.', 'تحكم في هوية المعهد والرسالة الأولى التي يراها الزوار.')}</div><div className="grid gap-5 md:grid-cols-2"><Field field="schoolName" label="School name" /><Field field="schoolNameAr" label="School name in Arabic" /></div><Field field="heroTitle" label="Hero headline" /><Field field="heroText" label="Hero introduction" area /></div>}
{section === 'homepage' && <div className="space-y-8"><section><h3 className="mb-4 font-display text-lg font-bold">{t('Why choose us', 'لماذا تختارنا')}</h3><Field field="whyTitle" label="Section heading" /><div className="mt-4 grid gap-4 md:grid-cols-2"><Field field="programQuran" label="Feature 1" /><Field field="programTarbiyah" label="Feature 2" /><Field field="programCommunity" label="Feature 3" /><Field field="program4" label="Feature 4" /><Field field="program5" label="Feature 5" /><Field field="program6" label="Feature 6" /></div></section><section className="border-t border-border pt-7"><h3 className="mb-4 font-display text-lg font-bold">{t('Academic programmes', 'البرامج الأكاديمية')}</h3><Field field="programTitle" label="Programmes heading" /><div className="mt-4 grid gap-4 md:grid-cols-2"><Field field="programme1" label="Programme 1" /><Field field="programme2" label="Programme 2" /><Field field="programme3" label="Programme 3" /><Field field="programme4" label="Programme 4" /><Field field="programme5" label="Programme 5" /><Field field="programme6" label="Programme 6" /></div></section><section className="border-t border-border pt-7"><h3 className="mb-4 font-display text-lg font-bold">{t('Prepared homepage sections', 'أقسام الصفحة الرئيسية الجاهزة')}</h3><div className="grid gap-4 md:grid-cols-2"><ListFields field="facilities" label="Facilities" /><ListFields field="galleryAlbums" label="Gallery albums" /><Field field="statsStudents" label="Students count" /><Field field="statsTeachers" label="Teachers count" /><Field field="statsGraduates" label="Graduates count" /><Field field="statsYears" label="Years of excellence" /></div></section></div>}
{section === 'pages' && <div className="space-y-8"><section><h3 className="mb-4 font-display text-lg font-bold">About page</h3><div className="grid gap-5 md:grid-cols-2"><Field field="aboutTitle" label="About heading" /><Field field="aboutText" label="About introduction" area /><Field field="history" label="History" area /><Field field="mission" label="Mission" area /><Field field="vision" label="Vision" area /><Field field="values" label="Core values" area /><Field field="philosophy" label="Educational philosophy" area /><Field field="headMessage" label="Head of institute message" area /></div></section><section className="border-t border-border pt-7"><h3 className="mb-4 font-display text-lg font-bold">Academics page</h3><div className="grid gap-5 md:grid-cols-2"><Field field="academicsIntro" label="Curriculum introduction" area /><Field field="curriculum" label="Curriculum overview" area /><Field field="methodology" label="Teaching methodology" area /><Field field="assessment" label="Assessment system" area /><Field field="calendar" label="Academic calendar" area /></div></section></div>}
{section === 'news' && <div className="space-y-6"><div className="rounded-lg border border-border bg-muted/40 p-5"><h3 className="font-display text-lg font-bold">News & Events CMS</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Create, edit, publish, unpublish, and delete the news and event items shown on the public website.</p><Link to="/admin/website/posts" className="mt-5 inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-bold text-primary-foreground hover:bg-primary/90"><Newspaper className="h-4 w-4" />Open post manager</Link></div></div>}
{section === 'gallery' && <div className="space-y-6"><div className="rounded-lg bg-muted/60 p-4 text-sm text-muted-foreground">{t('Manage images and albums shown on the public gallery.', 'إدارة الصور والألبومات الظاهرة في معرض الصور العام.')}</div><ListFields field="galleryImages" label="Gallery image paths" /><ListFields field="galleryAlbums" label="Gallery albums" /><div className="grid gap-3 sm:grid-cols-2">{content.galleryImages.split('|').filter(Boolean).map((image, index) => <div key={`${image}-${index}`} className="flex items-center gap-3 rounded-lg border border-border p-2"><img src={image} alt="" className="h-16 w-16 object-cover" /><span className="truncate text-xs text-muted-foreground">{image}</span></div>)}</div></div>}
{section === 'contact' && <div className="grid gap-5 md:grid-cols-2"><Field field="address" label="Address" area /><Field field="phone" label="Phone numbers" /><Field field="email" label="Email" /><Field field="officeHours" label="Office hours" /></div>}
</main></div></div></AdminLayout>;
};

export default AdminWebsite;
