// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtuvlxyekbptzwzkyllp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0dXZseHlla2JwdHp3emt5bGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMzkwODUsImV4cCI6MjA4NjkxNTA4NX0.BkGJXW8lmvanEv0lEGMDOBEMTtCwYMoZ3WuTSYVyefQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});